apiVersion: apps/v1
kind: Deployment

metadata:
  name: apaajabot
  labels:
    app: discordbot

spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: discordbot
        octopusexport: OctopusExport

    spec:
      containers:
        - name: apaajabot
          image: asia-southeast2-docker.pkg.dev/discord-bot-398115/apaajabot
