apiVersion: apps/v1
kind: Deployment

metadata:
  name: apaajabot
  labels:
    app: discordbot
    version: "3.0.0"
    environment: production

spec:
  selector:
    matchLabels:
      app: discordbot
  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: discordbot

    spec:
      containers:
        - name: apaajabot
          image: asia-southeast2-docker.pkg.dev/discord-bot-398115/apaajabot
