name: GKE
on:
  workflow_run:
    types: completed
    workflows: Docker build and push

env:
  project_id: ${{secrets.GKE_PROJECT}}
  GKE_CLUSTER: apa-ajabot # Add your cluster name here.

jobs:
  Kubernetes:
    name: Updating GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{secrets.GCP_CREDENTIALS}}
          token_format: access_token

      - name: Setup GKE
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: GKE_CLUSTER
          location: asia-southeast2-a

      - name: Deploy
        run: kubectl apply -f deployment.yaml
